---
id: tokyork-11
base_name: embed-ruby
tags:
- rabbit
- ruby
- embed
- milter-manager
- groonga
presentation_date: 2016-05-28
version: 2016.5.28.1
licenses:
- CC BY 3.0
- CC BY-SA 4.0
slideshare_id: tokyork-11
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
